### ISSUE TITLE
Different representation of the same object when serialization is repeated

### ISSUE THREAD

**Issue by Pryanic** [RuedigerMoeller/fast-serialization#206] opened 2017-07-28 12:01 UTC
After the first serialization in the json string,  FST adds a space at the beginning of the line.
![selection_495](https://user-images.githubusercontent.com/13783593/28716405-c25ba5f8-73a5-11e7-9136-5305aae3b5ef.png)
![selection_496](https://user-images.githubusercontent.com/13783593/28716404-c25705a2-73a5-11e7-9932-56577c44f263.png)

**Comment by aminka-16** [comment] 2017-07-28 13:26
+1, we've also faced the same problem with FST

**Comment by vgladush** [comment] 2017-07-28 13:36
+1 so I had the same problem

**Comment by RuedigerMoeller** [comment] 2017-07-31 09:19
ok,  that's strange

**Comment by RuedigerMoeller** [comment] 2017-07-31 09:44
btw, sending a cut and paste'able test case is strongly preferred over gifs ;)

**Comment by RuedigerMoeller** [comment] 2017-07-31 10:50
caused by missing reset of Jackson Stream generator. Unfortunately the reset method is protected and construction of Stream generator is not overrideable. Now create a new generator with each json serialization (no caching) as it seems Jackson factor does reuse behind the scenes anyway.

Fixed with 2.52

**Closed by RuedigerMoeller** 2017-07-31 10:50 UTC
Labels: bug, minor
