### ISSUE TITLE
RuntimeException: unknown object tag -19

### ISSUE THREAD

**Issue by hetzge** [RuedigerMoeller/fast-serialization#63] opened 2015-04-25 20:48 UTC
I get the following exception and don't know what it mean. Before the exception unreadable output is wrote to the console: http://i3.minus.com/ibal8jAVicKuSL.png
```
de.hetzge.sgame.common.exception.NetworkException: java.io.IOException: java.lang.RuntimeException: unknown object tag -19
	at de.hetzge.sgame.network.AcceptMessageThread.run(AcceptMessageThread.java:28)
Caused by: java.io.IOException: java.lang.RuntimeException: unknown object tag -19
	at org.nustaq.serialization.FSTObjectInput.readObject(FSTObjectInput.java:241)
	at org.nustaq.net.TCPObjectSocket.readObject(TCPObjectSocket.java:88)
	at de.hetzge.sgame.network.connection.FSTConnection.read(FSTConnection.java:19)
	at de.hetzge.sgame.network.AcceptMessageThread.run(AcceptMessageThread.java:26)
Caused by: java.lang.RuntimeException: unknown object tag -19
	at org.nustaq.serialization.FSTObjectInput.instantiateSpecialTag(FSTObjectInput.java:403)
	at org.nustaq.serialization.FSTObjectInput.readObjectWithHeader(FSTObjectInput.java:350)
	at org.nustaq.serialization.FSTObjectInput.readObjectFields(FSTObjectInput.java:659)
	at org.nustaq.serialization.FSTObjectInput.instantiateAndReadNoSer(FSTObjectInput.java:517)
	at org.nustaq.serialization.FSTObjectInput.readObjectWithHeader(FSTObjectInput.java:357)
	at org.nustaq.serialization.FSTObjectInput.readObjectFields(FSTObjectInput.java:659)
	at org.nustaq.serialization.FSTObjectInput.instantiateAndReadNoSer(FSTObjectInput.java:517)
	at org.nustaq.serialization.FSTObjectInput.readObjectWithHeader(FSTObjectInput.java:357)
	at org.nustaq.serialization.FSTObjectInput.readObjectFields(FSTObjectInput.java:659)
	at org.nustaq.serialization.FSTObjectInput.instantiateAndReadNoSer(FSTObjectInput.java:517)
	at org.nustaq.serialization.FSTObjectInput.readObjectWithHeader(FSTObjectInput.java:357)
	at org.nustaq.serialization.FSTObjectInput.readObjectFields(FSTObjectInput.java:659)
	at org.nustaq.serialization.FSTObjectInput.instantiateAndReadNoSer(FSTObjectInput.java:517)
	at org.nustaq.serialization.FSTObjectInput.readObjectWithHeader(FSTObjectInput.java:357)
	at org.nustaq.serialization.FSTObjectInput.readObjectFields(FSTObjectInput.java:659)
	at org.nustaq.serialization.FSTObjectInput.instantiateAndReadNoSer(FSTObjectInput.java:517)
	at org.nustaq.serialization.FSTObjectInput.readObjectWithHeader(FSTObjectInput.java:357)
	at org.nustaq.serialization.FSTObjectInput.readObjectFields(FSTObjectInput.java:659)
	at org.nustaq.serialization.FSTObjectInput.instantiateAndReadNoSer(FSTObjectInput.java:517)
	at org.nustaq.serialization.FSTObjectInput.readObjectWithHeader(FSTObjectInput.java:357)
	at org.nustaq.serialization.FSTObjectInput.readObjectInternal(FSTObjectInput.java:324)
	at org.nustaq.serialization.FSTObjectInput.readObject(FSTObjectInput.java:305)
	at org.nustaq.serialization.FSTObjectInput.readObject(FSTObjectInput.java:239)
	... 3 more
```

I use TCPObjectSocket for the communication.
What are the possible reasons for this exception ?

**Comment by RuedigerMoeller** [comment] 2015-04-25 21:00
1) which version are you using (+JDK + OS) ?
2) This is either stream corruption or deserialization failure. The string is printed from TCPObjectSocket.java *after* the exception occured.

to track down wether its network or serialization related, verify (debugcode at senderside) that all objects sent are properly de/encodable like ```Object test = myFSTConf.asObject( myFSTConf.asByteArray(objectToSend) );```
If this already fails, its a pure serialization issue, else its some issue in TCPObjectSocket.
In case it turns out to be a pure serialization issue, I need a reproducer to debug, because this can be tricky. What you can do is track down which classes make the error occur (e.g. by stepwise making fields transient in the object sent)

**Comment by RuedigerMoeller** [comment] 2015-05-05 17:13
closed as no feedback

**Closed by RuedigerMoeller** 2015-05-05 17:14 UTC
