### ISSUE TITLE
java.lang.NullPointerException: Class is null

### ISSUE THREAD

**Issue by rfer** [RuedigerMoeller/fast-serialization#69] opened 2015-06-05 16:22 UTC
Hi,

I recently bumped into the exception below using 1.63.

After looking at the code I see it's an expected exception at some point, but I'm find it difficult to really understand what went wrong.

I'm serializing and deserializing on different nodes, and the serialized binary is going throw the network. I can confirm that the class versions are the same on both ends, and this was a one-time exception (i.e. other events already went through this flow with success).

Could this be a problem during serialization? What are the expected scenarios that can cause this exception?

Thanks in advance

```
Caused by: java.lang.NullPointerException: Class is null 
        at de.ruedigermoeller.serialization.FSTClazzInfoRegistry.getCLInfo(FSTClazzInfoRegistry.java:128) 
        at de.ruedigermoeller.serialization.FSTObjectInput.getClazzInfo(FSTObjectInput.java:300) 
        at de.ruedigermoeller.serialization.FSTObjectInput.readObjectWithHeader(FSTObjectInput.java:250) 
        at de.ruedigermoeller.serialization.FSTObjectInput.readObjectInternal(FSTObjectInput.java:230) 
        at de.ruedigermoeller.serialization.serializers.FSTMapSerializer.instantiate(FSTMapSerializer.java:86) 
        at de.ruedigermoeller.serialization.FSTObjectInput.instantiateAndReadWithSer(FSTObjectInput.java:361) 
        at de.ruedigermoeller.serialization.FSTObjectInput.readObjectWithHeader(FSTObjectInput.java:260) 
        at de.ruedigermoeller.serialization.FSTObjectInput.readObjectFields(FSTObjectInput.java:544) 
        at de.ruedigermoeller.serialization.FSTObjectInput.instantiateAndReadNoSer(FSTObjectInput.java:406) 
        at de.ruedigermoeller.serialization.FSTObjectInput.readObjectWithHeader(FSTObjectInput.java:262) 
        at de.ruedigermoeller.serialization.FSTObjectInput.readObjectInternal(FSTObjectInput.java:230) 
        at de.ruedigermoeller.serialization.serializers.FSTArrayListSerializer.instantiate(FSTArrayListSerializer.java:71) 
        at de.ruedigermoeller.serialization.FSTObjectInput.instantiateAndReadWithSer(FSTObjectInput.java:361) 
        at de.ruedigermoeller.serialization.FSTObjectInput.readObjectWithHeader(FSTObjectInput.java:260) 
        at de.ruedigermoeller.serialization.FSTObjectInput.readObjectFields(FSTObjectInput.java:544) 
        at de.ruedigermoeller.serialization.FSTObjectInput.instantiateAndReadNoSer(FSTObjectInput.java:406) 
        at de.ruedigermoeller.serialization.FSTObjectInput.readObjectWithHeader(FSTObjectInput.java:262) 
        at de.ruedigermoeller.serialization.FSTObjectInput.readObjectInternal(FSTObjectInput.java:230) 
        at de.ruedigermoeller.serialization.FSTObjectInput.readObject(FSTObjectInput.java:210)
```

**Comment by RuedigerMoeller** [comment] 2015-06-05 19:19
If the stream read is somehow corrupted (e.g. missing bytes or asymmetric read/write implementation) anything can happen, so its mostly improbable to determine the root cause from the exception. "class is null" is typical for corrupted streams: a class tag is expected, but obviously its not a valid one.

1.63 is pretty old however this version is productive in a clustered application as remoting encoding for ~2 years, which means it shouldn't have too many bugs (anyway there are some corner cases that have been fixed in 2.x).

common reasons resulting in spurious (not deterministically reproducable) failures:
1) invalid multithreading 
- reuse same stream object from different threads
- mutate the object graph in another thread concurrently while its serialized
2) IO stream corruption. E.g. read streams chunked but fail to fetch the next block (typical offset 1 to small thingy or so) such that a random value is read from old buffer data. I recently fixed an issue in 2.x TCPObjectSocket which was present for a year without showing up:
```java
int read = in.read();
if ( read <= 0 ) // ERROR has to be < 0 !!!!!
    throw new EOFException("stream is closed");
```
3) messed up class registration order (must be identical for all members)

if the issue is deterministic (bound to a certain structure or class sequence being serialiezd):
- drill down a minimal error reproducer. There are still some weird edge cases where JDK classes (or third party stuff) read/write asymmetrically. I have catched most of these cases but I also had reports of unfixable stuff (e.g. serializing cross JDK from Android / Oracle).
- If its fixable its probably already fixed with 2.x
- Else write/register a custom serializer for the problematic class.

regards,
rüdiger

**Closed** 2017-04-10 15:58 UTC
Labels: question
