### ISSUE TITLE
BigDecimal using Oracle and IBM JDK 1.6

### ISSUE THREAD

**Issue by lodimas** [RuedigerMoeller/fast-serialization#51] opened 2015-01-28 16:28 UTC
Using version 1.63.

I am in an scenario where I serialize using IBM JDK 1.6, and I deserialize using Oracle JDK 1.6. BigDeciaml in those implementations differs, not having the same attributes, and both overriding readObject and writeObject. IBM's implementation makes sure the necessary fields for Oracle's implementation are written in the serialized data, having the following body:

```java
private synchronized void writeObject(ObjectOutputStream out)
    throws IOException
{
    ObjectOutputStream.PutField fields = out.putFields();

    fields.put("scale", scale());
    fields.put("intVal", unscaledValue());
    out.writeFields();
}
```
When deserializing, I got the following exception:

```java
Exception in thread "main" java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at de.ruedigermoeller.serialization.util.FSTUtil.rethrow(FSTUtil.java:119)
	at de.ruedigermoeller.serialization.FSTObjectInput.readObjectCompatibleRecursive(FSTObjectInput.java:474)
	at de.ruedigermoeller.serialization.FSTObjectInput.readObjectCompatible(FSTObjectInput.java:448)
	at de.ruedigermoeller.serialization.FSTObjectInput.instantiateAndReadNoSer(FSTObjectInput.java:399)
	at de.ruedigermoeller.serialization.FSTObjectInput.readObjectWithHeader(FSTObjectInput.java:262)
	at de.ruedigermoeller.serialization.FSTObjectInput.readObjectInternal(FSTObjectInput.java:230)
	at de.ruedigermoeller.serialization.FSTObjectInput.readObject(FSTObjectInput.java:210)
	at com.agabar.laboratory.serialization.Deserializer.deserialization(Deserializer.java:40)
	at com.agabar.laboratory.serialization.Deserializer.main(Deserializer.java:27)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at de.ruedigermoeller.serialization.FSTObjectInput.readObjectCompatibleRecursive(FSTObjectInput.java:471)
	... 7 more
Caused by: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at de.ruedigermoeller.serialization.util.FSTUtil.rethrow(FSTUtil.java:119)
	at de.ruedigermoeller.serialization.FSTObjectInput.readObjectCompatibleRecursive(FSTObjectInput.java:474)
	at de.ruedigermoeller.serialization.FSTObjectInput.readObjectCompatible(FSTObjectInput.java:448)
	at de.ruedigermoeller.serialization.FSTObjectInput.instantiateAndReadNoSer(FSTObjectInput.java:399)
	at de.ruedigermoeller.serialization.FSTObjectInput.readObjectWithHeader(FSTObjectInput.java:262)
	at de.ruedigermoeller.serialization.FSTObjectInput.readObjectFields(FSTObjectInput.java:544)
	at de.ruedigermoeller.serialization.FSTObjectInput$2.defaultReadObject(FSTObjectInput.java:1180)
	at de.ruedigermoeller.serialization.FSTObjectInput$MyObjectStream.defaultReadObject(FSTObjectInput.java:1481)
	at com.agabar.laboratory.serialization.Objekt.readObject(Objekt.java:27)
	... 12 more
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at de.ruedigermoeller.serialization.FSTObjectInput.readObjectCompatibleRecursive(FSTObjectInput.java:471)
	... 19 more
Caused by: java.io.StreamCorruptedException: BigDecimal: null intVal in stream
	at java.math.BigDecimal.readObject(BigDecimal.java:3551)
	... 24 more

```
This exception corresponds to Oracle's BigDecimal not receiving intVal, which was actually written when serializing. I suspect there is some inconsistency when written fields and actual fields differ.

I would appreciate any help regarding this issue.

I can provide sample code if you need so.

Thank you.

Dimas Cabré i Chacón

**Comment by RuedigerMoeller** [comment] 2015-01-28 17:04
First you might you check out the issues list for issues tagged "needs backport", there are some issues which have not been ported back to fast-serialization 1.x . Your issue might be affected by those fixes as they have to do with 'old' JDK serialization mechanics compatibility.

An easy workaround for a limited set of problematic classes is the definition & registration of custom serializers. Once a custom serializer is defined for a class, fst always uses it in favour of a provided read/writeObject implementation.

**Comment by lodimas** [comment] 2015-01-29 10:39
There seems to be no previous issue that targets the problem I reported.

I did further research, and I think I found where the problem comes from. In class `de.ruedigermoeller.serialization.FSTObjectInput`, at line *1776*, all fields that come from custom serialization through `ObjectOutputStream.PutField.put` method are read are placed in a `HashMap`. But it seems these information is not used later. In my opinion, we need to set these fields onto the target object. I added the following lines following line *1776*:
```java
final FSTClazzInfo.FSTFieldInfo[] fieldArray = clInfo.compInfo.get(cl).getFieldArray();                       
for (int i = 0; i < fieldArray.length; i++) {
   FSTClazzInfo.FSTFieldInfo fstFieldInfo = fieldArray[i];
   final Object val = fieldMap.get(fstFieldInfo.getField().getName());
   if ( val != null ) {
   fstFieldInfo.setObjectValue(toRead,val);
}
```

This way, the problem seems to be fixed.

I would appreciate a lot if you could confirm the root cause and fix are right, or if there is an alternative way to accomplish the same without using custom serializers. In case of a positive answer, I would thank you if you could release a new 1.x version with the fix.

Thank you in advance.

Dimas Cabré i Chacón

**Comment by RuedigerMoeller** [comment] 2015-01-29 12:15
The putfield variants work usually (many testcases in 2.x cover that ).
What's the problem is, that JDK Serialization implicitely assumes, that the
values written by the putField variant are binary compatible to
defaultReadObject and can be read later on using e.g. defaultReadObejct.
Therefore I added special tags into the stream so I can recognize at
readtime, which method has been used on write time. These fixes have not
reconciled back to the 1.x branch so I'd assume this is the reason.
Unfortunately 1.x has no proper test cases and I can tell you changing
stuff in the area of JDK-compatibility is very dangerous. Usually a fix for
one case breaks other use cases.

Can you provide me with a reproducer ? I will have a look as is find time
(I'm at work currently ..). Ofc I'll check your fix, however I'd like to
first verify if its fixed by backporting some of the 2.x issues, as they
have been proven to work without breaking other variants.

Regarding "Custom Serializer": If a FSTSerializer is registered at
FSTConfiguration, putField should not be called at all, so I am somewhat
confused now :-)

2015-01-29 11:39 GMT+01:00 Dimas Cabré i Chacón <notifications@github.com>:

**Comment by RuedigerMoeller** [comment] 2015-01-29 12:38
issue #39 is related to something very similar (getField/putField used on write but not on read in Vector or so) 
though my initial analysis was wrong, scroll down ..

best way for you would be registering a custom serializer and continue. I'll have time at friday to backport 2.x testcases. Its incredibly easy to break things :-). Seems like i have to prepare for a longer 1.x maintenance period :-)

It would be very helpful if you could provide a simpel reproducer. Does it also fail oracle <=> oracle or only IBM <=> oracle ?

**Comment by RuedigerMoeller** [comment] 2015-01-29 12:47
Regarding your fix: there are tons of testcases covering correct behaviour of get/putfield so I'd assume it should be correct. However what do know :) , I really have to find time for a deep look. In any case thanks for your help+analysis in advance ... stay tuned

**Comment by lodimas** [comment] 2015-01-29 18:17
Hello.

I try to answer to all your questions and give you further feedback.

I understand my problem could be fixed with some backporting. I would greatly appreciate if you could work on it in a short time. Please, let me know if I can help you in any way. 

I prepared two files were the result of serializing with Oracle and IBM JDK is written. I cannot see how to attach them. Please, let me know how can I make them available to you. Assuming these files, here is the simple code that tries to deserialize the stream in the file:
```java
package com.agabar.laboratory.serialization;

import java.io.ByteArrayInputStream;
import java.io.File;
import java.io.IOException;
import java.math.BigDecimal;

import org.apache.commons.io.FileUtils;

import de.ruedigermoeller.serialization.FSTConfiguration;
import de.ruedigermoeller.serialization.FSTObjectInput;

public class Deserializer
{

	private static final FSTConfiguration fstConfiguration = FSTConfiguration.createDefaultConfiguration ();

	public static void main (String [] arguments) throws IOException, Exception
	{
		fstConfiguration.registerClass (BigDecimal.class);
		@SuppressWarnings ("unused")
		BigDecimal bigDecimal = deserialization ();
	}

	private static BigDecimal deserialization () throws Exception
	{
		FSTObjectInput fstObjectInput = null;
		ByteArrayInputStream byteArrayInputStream = null;

		try
		{
			byte [] data = FileUtils.readFileToByteArray (new File ("c:/" + BigDecimal.class.getName () + ".ibm" + ".dat"));
			byteArrayInputStream = new ByteArrayInputStream (data);
			fstObjectInput = fstConfiguration.getObjectInput (byteArrayInputStream);
			BigDecimal bigDecimal = (BigDecimal) fstObjectInput.readObject (BigDecimal.class);
			return bigDecimal;
		}
		finally
		{
			byteArrayInputStream.close ();
		}
	}
}
```
I can send you a whole simple Eclipse project if you can tell me how to send it to you. 

As for your last question, deserialization goes wrong when mixing JDK's. That is:
IBM --> Oracle: fail
Oracle --> IBM: fail
IBM --> IBM: success
Oracle --> Oracle: success

Additionally, I found my previous solution contains a bug. As you can see, I used method `setObjectValue` to set the value for the extra fields. This method is wrong and not working for primitive types, as the dedicated method for the primitive type has to be used. That's what you already do in method `readObjectFields` in the same class. Unfortunately, this method gives me problems for non primitive types. I coded a workaround spliting primitive and non primitive fields into two arrays, and setting their corresponding values with different working strategies. I am aware this is far from perfect and might mean I am not understanding something from your code. Still, you use the same `setObjectValue` some lines above, as I mentioned in my previous post, so your code might contain the same problem I am facing.

For you reference, here is the final block of code I added after line *1776* (I am sure you will want to rewrite it in a more elegant and efficient way...):

```java
final FSTClazzInfo.FSTFieldInfo[] fieldArray = clInfo.compInfo.get(cl).getFieldArray();

// We split primitive fileds and reference fileds
FSTClazzInfo.FSTFieldInfo[] fieldInfo =  clInfo.compInfo.get(cl).getFieldArray();
ArrayList<FSTClazzInfo.FSTFieldInfo> fieldInfoPrimitive = new ArrayList<FSTClazzInfo.FSTFieldInfo> ();
ArrayList<FSTClazzInfo.FSTFieldInfo> fieldInfoReference = new ArrayList<FSTClazzInfo.FSTFieldInfo> ();                        
final int length = fieldInfo.length;
for (int i = 0; i < fieldInfo.length; i++) {
	FSTClazzInfo.FSTFieldInfo subInfo = fieldInfo[i];
	 if (subInfo.isPrimitive()) {
		 fieldInfoPrimitive.add (subInfo);
	 } else {
		 fieldInfoReference.add (subInfo);
	 }                               
}                

// Put primitive fields using standard method that already forks by type
FSTObjectInput.this.readObjectFields(
	 referencee,
	 clInfo,
	 fieldInfoPrimitive.toArray (new FSTClazzInfo.FSTFieldInfo [fieldInfoPrimitive.size ()]),
	 toRead
);                        

// Put reference fields usingt forced setObjectValue, as previous method crashes for reference fields
FSTClazzInfo.FSTFieldInfo[] fieldArrayReference = fieldInfoReference.toArray (new FSTClazzInfo.FSTFieldInfo [fieldInfoReference.size ()]);                        
for (int i = 0; i < fieldArrayReference.length; i++) {
	FSTClazzInfo.FSTFieldInfo fstFieldInfo = fieldArrayReference[i];
	final Object val = fieldMap.get(fstFieldInfo.getField().getName());
	if ( val != null ) {
		fstFieldInfo.setObjectValue(toRead, val);
	}
}
```

Finally: ¿Could you explain me how to run the 1.* tests? I see they cannot be compiled with JDK 1.6, so I am not sure whether I am doing something wrong or not.

**Comment by RuedigerMoeller** [comment] 2015-01-29 18:55
To explain the root problem:
one class uses .. putField(..); ... outstream.writeFields .. but the reader side impl. then uses something like instream.defaultReadObject(). The JDK expectation is, that writeFields and e.g. defaultWirteObject() create binary compatible output. But this does not hold true for fast-ser, as I optimized the defaultWriteObject a lot, so I don't write field names and stuff, so it works only if the read and write side use the same method to read/write data.
The solution I applied in 2.x was to put something in at writer side like writeFields() { stream.writeByte(99); .. } so I can detect during read, which method has been used on writer side and can branch to an appropriate read method.

I'll provide you with a FSTSerializer based workaround as I am short of time, and will deliver a proper fix later. The 1.x tests are a complete mess, I added proper testing in 2.x only :-).

**Comment by RuedigerMoeller** [comment] 2015-01-29 18:56
Here is an outline how to workaround issues like yours. Must be applied symmetrically to reading and writing application

```java
public class FSTBigDecimalSerializer extends FSTBasicObjectSerializer {
    @Override
    public void writeObject(FSTObjectOutput out, Object toWrite, FSTClazzInfo clzInfo, FSTClazzInfo.FSTFieldInfo referencedBy, int streamPosition) throws IOException {
        BigDecimal bd = (BigDecimal) toWrite;
        out.writeCInt(bd.scale());
        out.writeObject(bd.toBigInteger().toByteArray());
    }

    @Override
    public Object instantiate(Class objectClass, FSTObjectInput in, FSTClazzInfo serializationInfo, FSTClazzInfo.FSTFieldInfo referencee, int streamPositioin) throws IOException, ClassNotFoundException, InstantiationException, IllegalAccessException {
        int scale = in.readCInt(); // read"C"Int means compressed int
        BigDecimal bigDecimal = new BigDecimal( new BigInteger((byte[]) in.readObject()), scale);
        // need to register for ref restauration
        in.registerObject(bigDecimal,streamPositioin,serializationInfo,referencee);
        return bigDecimal;
    }


    public static void main( String arg[] ) {
        // init static conf
        /* public static */FSTConfiguration conf = FSTConfiguration.createDefaultConfiguration();
        conf.registerSerializer(BigDecimal.class, new FSTBigDecimalSerializer(),false);

        // later
        InputStream instream = null;
        FSTObjectInput in = new FSTObjectInput(instream,conf);
        // or
        // conf.getObjectInput(..)
        //...
        
        // similar with output
    }
}
```

**Comment by lodimas** [comment] 2015-01-30 07:49
Thank you for your response and code! I tested it and it works perfect!

I will wait for you 1.* fix during next week. Please, let me know if you want me to do some testing using distinct source and target VMs before releasing the next version.

Thank you again.

**Comment by RuedigerMoeller** [comment] 2015-01-30 15:19
thanks for helping. Note Serializers can be used to fix most cross JDK Issues as long it a limited set of problems/incompatible classes.

**Comment by RuedigerMoeller** [comment] 2015-02-01 12:07
I decided to not longer provide fixes for ancient releases because
a) most of them can be workarounded using FSTSerializers
b) There is no testsuite for 1.x, so its extremely easy to break cornercases
c) there is a small audience for ancient releases and edgy stuff like oracle<=>ibm jdk 1.6 interop
d) my time is not for free :-)

I'll still help by analysing and will mark fixes for 2.x with a "needsbackport" tag.
You can either workaround as described above, backport yourself or in case of production-critical need for 1.x ancient jdk release fixes contact me at my gmail _ com account under moru0011 for commercial support.

**Closed by RuedigerMoeller** 2015-02-01 12:07 UTC
