### ISSUE TITLE
FSTInputStream.readNextChunk swallows Exception silently 

### ISSUE THREAD

**Issue by ghost** [RuedigerMoeller/fast-serialization#143] opened 2016-07-29 14:07 UTC
FSTInputStream.readNextChunk contains the code:
```
try {
            ...
} catch (Exception iex) {
    fullyRead = true;
}
```

Later, you will get an exception anyway (like "class not found CLASSNAME: loader:sun.misc.Launcher$AppClassLoader@18b4aac2"), but it has nothing to do with the original exception, which FSTInputStream silently ignores.

**Comment by RuedigerMoeller** [comment] 2016-07-29 14:17
Yes, that's ugly, but caused by half-baked stream implementations throwing exceptions instead of returning the number of read bytes (should be 0 at end of stream). Throwing the exception will probably will break stuff (and nowadays there are many projects relying on fst). 

```java
    public void readNextChunk(InputStream in) {
        int read;
        try {
            ....
            read = in.read(buf, count, chunk_size);
            if (read > 0) {
                count += read;
            } else {
                fullyRead = true;
            }
        } catch (Exception iex) {
            fullyRead = true;
        }
    }
```
So I tend to wontfix, but add a comments to this place

**Closed** 2016-08-05 18:12 UTC
Labels: wontfix
